#!/bin/bash
read -n 1 -p "hi are y sure that y want to run this (y/[a]): " AMSURE 
[ "$AMSURE" = "y" ] || exit
echo "" 1>&2
echo "this is your local time:"
T=$(date +%H:%M:%S)
D=$(date +%Y-%m-%d)
echo "$T" "$D"

This is the last file in the project right now
